"""Supabase (service-role) writer — only the worker uses these helpers."""

from eyesinvest_worker.db.supabase import (
    fetch_active_stocks,
    fetch_active_stocks_with_sector,
    fetch_existing_news_urls,
    fetch_last_settlement_date,
    fetch_latest_short_interest,
    fetch_latest_short_sale,
    fetch_news_article_id,
    fetch_price_history,
    make_client,
    upsert_analytics_rows,
    upsert_fundamentals,
    upsert_index_quotes,
    upsert_news_articles,
    upsert_news_stock_mappings,
    upsert_price_bars,
    upsert_quote_snapshot,
    upsert_sector_daily,
    upsert_short_interest,
    upsert_short_sales,
    upsert_stock_relationships,
)

__all__ = [
    "fetch_active_stocks",
    "fetch_active_stocks_with_sector",
    "fetch_existing_news_urls",
    "fetch_last_settlement_date",
    "fetch_latest_short_interest",
    "fetch_latest_short_sale",
    "fetch_news_article_id",
    "fetch_price_history",
    "make_client",
    "upsert_analytics_rows",
    "upsert_fundamentals",
    "upsert_index_quotes",
    "upsert_news_articles",
    "upsert_news_stock_mappings",
    "upsert_price_bars",
    "upsert_quote_snapshot",
    "upsert_sector_daily",
    "upsert_short_interest",
    "upsert_short_sales",
    "upsert_stock_relationships",
]
